<expr>			:== <term> <expr_tail>
<expr_tail>		:== '+' <term> <expr_tail> | '-' <term> <expr_tail> | epsilon
<term>			:== <unary> <term_tail>
<term_tail>		:== '*' <unary> <term_tail> | '/' <unary> <term_tail>
					'%' <unary> <term_tail> | epsilon
<unary>			:== '+' <unary> | '-' <unary> | <factor>
<factor>		:== <base> <factor_tail> | <base>
<factor_tail>	:== '^' <factor>
<base>			:== '(' <expr> ')' | Num | Real
<exponent>		:== <base>
