<expr>			:== <term> <expr_tail>
<expr_tail>		:== '+' <term> <expr_tail> | '-' <term> <expr_tail> | epsilon
<term>			:== <unary> <term_tail>
<term_tail>		:== '*' <unary> <term_tail> | '/' <unary> <term_tail>
					'%' <unary> <term_tail> | epsilon
<unary>			:== '+' <unary> | '-' <unary> | <factor>
<factor>		:== <base> <factor_tail> | <base>
<factor_tail>	:== '^' <unary>
<base>			:== '(' <expr> ')' | <vector> | <matrix> | Rational | Complex
<exponent>		:== <base>
<vector>		:== '[' <vector_tail> ']'
<vector_tail>	:== <expr> ',' <vector_tail> | <expr>
<matrix>		:== '[' <matrix_tail> ']'
<matrix_tail>	:== <vector> ';' <matrix_tail> | <vector>
